/**
 * map-rotation — Drop G. The numbers in `docs/MAP_2.md` are measured here, not guessed.
 *
 * Run:  ./apps/server/node_modules/.bin/tsx apps/client/e2e/tools/map-rotation.ts \
 *         > apps/client/e2e/out/g/rotation.md
 *
 * It runs the REAL shared simulation (`simulateBody`) — the same code the server ticks and the
 * client predicts with — and reports four things:
 *   1. the movement model: steady speeds, the acceleration ramp, stop distance;
 *   2. what a corner and a flight of stairs actually cost in this model (answer: nothing);
 *   3. NIGHT_DISTRICT's real rotations, walked on its real walk grid with its real geometry, and
 *      its sight-line distribution — the reference the second map is compared against;
 *   4. the drafted GÓRA routes and sight lines (a polyline on flat ground: the geometry does not
 *      exist yet, so these are the drawn distances timed with the real movement model).
 */
import { CollisionWorld, boxFrom, makeRayHit } from "../../../../packages/shared/src/collision";
import { PLAYER } from "../../../../packages/shared/src/constants";
import { createBody, simulateBody, TAC, MOVE } from "../../../../packages/shared/src/movement";
import { Btn } from "../../../../packages/shared/src/types";
import { NIGHT_DISTRICT, buildCollisionWorld } from "../../../../packages/shared/src/map";
import { GORA } from "../../../../packages/shared/src/gora";
import { walkable, reachable, cellKey, WALK_GRID } from "../../../../packages/shared/src/mapWalk";
import { prepareNav, findPath } from "../../../../packages/shared/src/nav";

const DT = 1000 / 60;
type P = [number, number];

const flatWorld = (): CollisionWorld => {
  const w = new CollisionWorld();
  w.addBoxes([boxFrom(-200, -1, -200, 400, 1, 400)]);
  return w;
};
const inp = (seq: number, buttons: number, yaw: number) => ({ seq, dt: DT, buttons, yaw, pitch: 0 });
const line = (a: P, b: P) => Math.hypot(a[0] - b[0], a[1] - b[1]);
const polyLen = (p: P[]) => p.slice(1).reduce((a, c, i) => a + line(p[i], c), 0);
const rnd32 = (seed: number) => () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

function profile(name: string, buttons: number, scale = 1): void {
  const w = flatWorld();
  const b = createBody(0, 0, 0);
  b.grounded = true;
  let seq = 0;
  const v: number[] = [];
  for (let i = 0; i < 360; i++) {
    const px = b.x, pz = b.z;
    simulateBody(w, b, inp(seq++, buttons, 0), scale, buttons);
    v.push(Math.hypot(b.x - px, b.z - pz) / (DT / 1000));
  }
  const steady = v.slice(-60).reduce((a, c) => a + c, 0) / 60;
  const b2 = createBody(0, 0, 0); b2.grounded = true; seq = 0;
  let t90 = -1, d90 = 0, t = 0;
  for (let i = 0; i < 360; i++) {
    const px = b2.x, pz = b2.z;
    simulateBody(w, b2, inp(seq++, buttons, 0), scale, buttons);
    t += DT;
    if (t90 < 0 && Math.hypot(b2.x - px, b2.z - pz) / (DT / 1000) >= steady * 0.9) { t90 = t; d90 = Math.hypot(b2.x, b2.z); }
  }
  const b3 = createBody(0, 0, 0); b3.grounded = true; seq = 0;
  for (let i = 0; i < 180; i++) simulateBody(w, b3, inp(seq++, buttons, 0), scale, buttons);
  const sx = b3.x, sz = b3.z;
  for (let i = 0; i < 300; i++) simulateBody(w, b3, inp(seq++, 0, 0), scale, buttons);
  console.log(`| ${name} | ${steady.toFixed(2)} | ${t90.toFixed(0)} ms / ${d90.toFixed(2)} m | ${Math.hypot(b3.x - sx, b3.z - sz).toFixed(2)} m |`);
}

function runRoute(world: CollisionWorld, pts: P[], y = 0, buttons = Btn.Forward | Btn.Sprint): { s: number; stuck: boolean } {
  const b = createBody(pts[0][0], y, pts[0][1]);
  b.grounded = true;
  let seq = 0, t = 0, target = 1, lastProgress = 0, stuck = false;
  while (target < pts.length) {
    const dx = pts[target][0] - b.x, dz = pts[target][1] - b.z;
    if (Math.hypot(dx, dz) < 0.6) { target++; continue; }
    const px = b.x, pz = b.z;
    simulateBody(world, b, inp(seq++, buttons, Math.atan2(dx, dz)), 1, buttons);
    t += DT;
    if (Math.hypot(b.x - px, b.z - pz) > 0.02) lastProgress = t;
    if (t - lastProgress > 1500 || t > 120000) { stuck = true; break; }
  }
  return { s: t / 1000, stuck };
}

const table = (rows: [string, P[]][]) => {
  for (const [name, pts] of rows) {
    const r = runRoute(flatWorld(), pts);
    console.log(`| ${name} | ${polyLen(pts).toFixed(1)} | ${r.s.toFixed(1)} |`);
  }
};

console.log(`# Drop G — measured movement, rotations and sight lines\n`);
console.log(`Generated by \`apps/client/e2e/tools/map-rotation.ts\` (real \`simulateBody\`, 60 Hz).\n`);

console.log(`## 1. The movement model\n`);
console.log(`Constants: walk ${PLAYER.walkSpeed}, sprint ${PLAYER.sprintSpeed}, crouch ${PLAYER.crouchSpeed} m/s; ground accel ${PLAYER.groundAccel}, friction ${PLAYER.friction}; tac sprint ×${TAC.speedScale} (budget ${TAC.budgetMs} ms), ADS ×${MOVE.adsSpeedScale}; step height ${PLAYER.stepHeight} m.\n`);
console.log(`| Gait | Steady (m/s) | 90 % of top after | Stop distance |`);
console.log(`|---|---|---|---|`);
profile("walk (W)", Btn.Forward);
profile("sprint (W+Shift)", Btn.Forward | Btn.Sprint);
profile("tac sprint (double-tap Shift)", Btn.Forward | Btn.Sprint | Btn.Tac);
profile("crouch (W+Ctrl)", Btn.Forward | Btn.Crouch);
profile("ADS walk (×0.8)", Btn.Forward | Btn.Aim, MOVE.adsSpeedScale);
profile("strafe (D)", Btn.Right);

console.log(`\n## 2. What corners and stairs cost\n`);
console.log(`| Route | Path (m) | Time (s) | Effective (m/s) |`);
console.log(`|---|---|---|---|`);
for (const [name, pts] of [
  ["straight 20 m", [[0, 0], [0, 20]]],
  ["one 90° corner (10+10)", [[0, 0], [0, 10], [10, 10]]],
  ["two 90° corners (7+6+7)", [[0, 0], [0, 7], [6, 7], [6, 14]]],
  ["four 90° corners (5×5)", [[0, 0], [0, 5], [5, 5], [5, 10], [10, 10], [10, 15]]],
] as [string, P[]][]) {
  const r = runRoute(flatWorld(), pts);
  console.log(`| ${name} | ${polyLen(pts).toFixed(1)} | ${r.s.toFixed(2)} | ${(polyLen(pts) / r.s).toFixed(2)} |`);
}
{
  const w = new CollisionWorld();
  const boxes = [boxFrom(-5, -1, -8, 20, 1, 30)];
  for (let i = 0; i < 9; i++) boxes.push(boxFrom(-1, 0, i * 0.5, 2, (i + 1) * 0.3334, 0.5));
  boxes.push(boxFrom(-1, 0, 4.5, 2, 3.0, 6));
  w.addBoxes(boxes);
  const climb = (world: CollisionWorld) => {
    const b = createBody(0, 0, -4); b.grounded = true;
    let seq = 0, t = 0;
    while (b.z < 7 && t < 20000) { simulateBody(world, b, inp(seq++, Btn.Forward | Btn.Sprint, 0), 1, Btn.Forward | Btn.Sprint); t += DT; }
    return { t: t / 1000, y: b.y };
  };
  const up = climb(w), flat = climb(flatWorld());
  console.log(`| 11 m including a 3.0 m stair (9 × 0.333 m rise) | 11.0 | ${up.t.toFixed(2)} | — (ends at y=${up.y.toFixed(2)}) |`);
  console.log(`| the same 11 m flat | 11.0 | ${flat.t.toFixed(2)} | — |`);
  console.log(`\nA corner and a stair are **free** in this model: acceleration is proportional to the wish speed and the step-up sweep does not shed velocity. Height costs exposure, not time.\n`);

  // Sprint jump: how wide a gap the movement model actually clears, and how high a jump reaches.
  const g = flatWorld();
  const b = createBody(0, 0, 0); b.grounded = true;
  let seq = 0;
  for (let i = 0; i < 60; i++) simulateBody(g, b, inp(seq++, Btn.Forward | Btn.Sprint, 0), 1, Btn.Forward | Btn.Sprint);
  const z0 = b.z;
  simulateBody(g, b, inp(seq++, Btn.Forward | Btn.Sprint | Btn.Jump, 0), 1, Btn.Forward | Btn.Sprint);
  let apex = 0, air = 0;
  while (!b.grounded && air < 3000) {
    simulateBody(g, b, inp(seq++, Btn.Forward | Btn.Sprint, 0), 1, Btn.Forward | Btn.Sprint | Btn.Jump);
    apex = Math.max(apex, b.y); air += DT;
  }
  console.log(`**Sprint jump:** ${(b.z - z0).toFixed(2)} m of ground covered, apex ${apex.toFixed(2)} m, ${air.toFixed(0)} ms in the air. A gap wider than ${(b.z - z0).toFixed(1)} m cannot be jumped.\n`);
}

console.log(`\n## 3. NIGHT_DISTRICT — the reference (real geometry, real walk grid)\n`);
const nd = buildCollisionWorld(NIGHT_DISTRICT);
const walk = walkable(NIGHT_DISTRICT);
prepareNav(walk);
const t0 = NIGHT_DISTRICT.spawns.find((s) => s.team === 0)!;
const t1 = NIGHT_DISTRICT.spawns.find((s) => s.team === 1)!;
console.log(`| Rotation | Straight (m) | Path (m) | Sprint (s) |`);
console.log(`|---|---|---|---|`);
for (const [name, from, to] of [
  ["bomb A DEPOT → bomb B COURTYARD", { x: -35, y: 0.2, z: 24 }, { x: 43, y: 0.2, z: 24 }],
  ["team 0 spawn → site A", { x: t0.x, y: t0.y, z: t0.z }, { x: -35, y: 0.2, z: 24 }],
  ["team 0 spawn → site B", { x: t0.x, y: t0.y, z: t0.z }, { x: 43, y: 0.2, z: 24 }],
  ["team 1 spawn → site A", { x: t1.x, y: t1.y, z: t1.z }, { x: -35, y: 0.2, z: 24 }],
  ["team 0 spawn → flag B (the shop)", { x: t0.x, y: t0.y, z: t0.z }, { x: 3.4, y: 0.2, z: 7.2 }],
  ["team 0 spawn → team 1 spawn", { x: t0.x, y: t0.y, z: t0.z }, { x: t1.x, y: t1.y, z: t1.z }],
] as [string, { x: number; y: number; z: number }, { x: number; y: number; z: number }][]) {
  const path = findPath(walk, from, to, 60000);
  if (!path) { console.log(`| ${name} | — | NO PATH | — |`); continue; }
  const pts: P[] = path.map((p) => [p.x, p.z]);
  const r = runRoute(nd, pts, from.y);
  console.log(`| ${name} | ${Math.hypot(to.x - from.x, to.z - from.z).toFixed(1)} | ${polyLen(pts).toFixed(1)} | ${r.stuck ? (polyLen(pts) / 7.6).toFixed(1) + " (est)" : r.s.toFixed(1)} |`);
}
{
  const cells: { x: number; z: number; y: number }[] = [];
  for (const [key, ys] of walk.cells) {
    const [cx, cz] = key.split(",").map(Number);
    for (const y of ys) cells.push({ x: cx / 2, z: cz / 2, y });
  }
  const rnd = rnd32(12345);
  const clear: number[] = [];
  let max = 0, N = 400000;
  for (let i = 0; i < N; i++) {
    const a = cells[(rnd() * cells.length) | 0], b = cells[(rnd() * cells.length) | 0];
    const dx = b.x - a.x, dy = b.y - a.y, dz = b.z - a.z;
    const len = Math.hypot(dx, dy, dz);
    if (len < 1) continue;
    if (!nd.raycast(a.x, a.y + PLAYER.eyeHeight, a.z, dx / len, dy / len, dz / len, len - 0.05, makeRayHit()).hit) {
      clear.push(len);
      if (len > max) max = len;
    }
  }
  clear.sort((p, q) => p - q);
  const pc = (f: number) => clear[Math.floor(clear.length * f)].toFixed(1);
  const over = (m: number) => ((clear.filter((c) => c >= m).length / clear.length) * 100).toFixed(1);
  const ndReach = reachable(walk, NIGHT_DISTRICT.spawns[0]);
  console.log(`\n**Sight lines.** ${walk.cells.size} walkable cells at ${WALK_GRID} m (${ndReach.size} surfaces reachable from spawn 0 = ${(ndReach.size * WALK_GRID * WALK_GRID).toFixed(0)} m²). ${N} random eye-to-eye pairs, ${clear.length} unobstructed (${((clear.length / N) * 100).toFixed(1)} %):`);
  console.log(`median **${pc(0.5)} m**, p90 ${pc(0.9)} m, p99 ${pc(0.99)} m, longest **${max.toFixed(1)} m**.`);
  console.log(`Of the clear lines, ${over(20)} % are over 20 m, ${over(30)} % over 30 m, ${over(50)} % over 50 m.\n`);
}

console.log(`\n## 4. GÓRA — the drafted routes (polyline on flat ground; geometry does not exist yet)\n`);
console.log(`| Rotation | Path (m) | Sprint (s) |`);
console.log(`|---|---|---|`);
table([
  ["T0 spawn → bomb B HOL (0,0)", [[-13, -2.5], [-9.5, -0.2], [-4, 0], [0, 0]]],
  ["T1 spawn → bomb B HOL (0,0)", [[13, -2.5], [9.5, -0.2], [4, 0], [0, 0]]],
  ["T0 spawn → bomb A BALKON (0,10), west ring", [[-13, -2.5], [-12.5, 1], [-12, 5], [-9.5, 6], [-6, 8], [0, 10]]],
  ["T1 spawn → bomb A BALKON (0,10), east ring", [[13, -2.5], [12.5, 1], [12, 5], [9.5, 6], [6, 8], [0, 10]]],
  ["T0 spawn → bomb A, inner (core passage)", [[-13, -2.5], [-9, 0], [-3.2, 0], [-3.2, 3], [-3.2, 6], [-6, 8], [0, 10]]],
  ["site B HOL ↔ site A BALKON (core passage)", [[0, 0], [3.2, 1], [3.2, 4], [3.2, 6.5], [6, 8], [0, 10]]],
  ["site B HOL ↔ site A BALKON (west wing)", [[0, 0], [-6, 0], [-9.5, 1], [-12, 5], [-9.5, 6], [-6, 8], [0, 10]]],
  ["T0 spawn → flag A SALON (home)", [[-13, -2.5], [-13, -3]]],
  ["T0 spawn → flag C BALKON", [[-13, -2.5], [-12.5, 1], [-12, 5], [-9.5, 6], [-6, 8], [0, 10]]],
  ["T1 spawn → flag C BALKON", [[13, -2.5], [12.5, 1], [12, 5], [9.5, 6], [6, 8], [0, 10]]],
  ["T0 spawn → flag B SYPIALNIA (the far flag)", [[-13, -2.5], [-9, 0], [0, 0], [9, 0], [13, -3]]],
  ["T0 spawn → T1 spawn (first contact)", [[-13, -2.5], [-9, 0], [0, 0], [9, 0], [13, -2.5]]],
  ["KUCHNIA → SKŁAD (the north crossing, blocked by the well)", [[-13, 6.5], [-9.5, 6], [-6, 8], [6, 8], [9.5, 6], [13, 6.5]]],
  ["balcony east → roof (fire escape, +2.9 m)", [[11, 10], [14, 10], [16, 9], [16, 6]]],
  ["SKŁAD → roof (shelf + hatch, +2.9 m)", [[13, 6.5], [11.5, 6.2], [11, 6]]],
  ["roof north parapet → the balcony (0,10)", [[11, 7.5], [13, 9], [11, 10], [0, 10]]],
  ["ŁAZIENKA → south hall (the dead end)", [[0.5, -4], [0.5, -1.5], [0.5, 0]]],
]);

console.log(`\n## 5. GÓRA — the drafted sight lines (straight line, metres)\n`);
console.log(`| Line | m |`);
console.log(`|---|---|`);
for (const [name, a, b] of [
  ["BALKON, west end → east end (the long one)", [-8, 10], [12, 10]],
  ["HOL POŁUDNIOWY, salon door → bedroom door", [-8, 0], [8, 0]],
  ["DACH, south-west corner → north-east corner", [6, -2], [17, 8]],
  ["DACH north parapet → bomb site A on the balcony", [11, 8], [0, 10]],
  ["DACH north parapet → the balcony's west end", [8, 8], [-8, 10]],
  ["SALON, corner to corner", [-17, -7], [-8, 1]],
  ["SYPIALNIA, corner to corner", [8, 1], [17, -7]],
  ["KUCHNIA, corner to corner", [-8, 3], [-17, 9]],
  ["SKŁAD, corner to corner", [8, 3], [17, 9]],
  ["HOL PÓŁNOCNY, west leg corner to corner", [-8, 5], [-2.5, 9]],
  ["across the SZYB (the light well)", [-2.5, 7], [2.5, 7]],
  ["ŁAZIENKA, door → far corner", [0.5, -1], [-2, -6]],
] as [string, P, P][]) console.log(`| ${name} | ${line(a, b).toFixed(1)} |`);

// ---------------------------------------------------------------------------------------------
// 6. GÓRA as BUILT. Sections 4 and 5 above are the drafted polylines that were signed off; this
//    section re-measures the same routes on the real geometry and the real walk grid, so the doc's
//    "As built" table is a measurement rather than a drawing.
// ---------------------------------------------------------------------------------------------
console.log(`\n## 6. GÓRA as built (real geometry, real walk grid)\n`);
const gora = buildCollisionWorld(GORA);
const gwalk = walkable(GORA);
prepareNav(gwalk);
const g0 = GORA.spawns.find((s) => s.team === 0)!;
const g1 = GORA.spawns.find((s) => s.team === 1)!;
const gsite = (id: string) => { const s = GORA.sites!.find((v) => v.id === id)!; return { x: s.x, y: 0, z: s.z }; };
const gflag = (id: string) => { const f = GORA.flags.find((v) => v.id === id)!; return { x: f.x, y: 0, z: f.z }; };
console.log(`| Rotation | Straight (m) | Path (m) | Sprint (s) |`);
console.log(`|---|---|---|---|`);
for (const [name, from, to] of [
  ["T0 spawn → bomb B HOL", { x: g0.x, y: g0.y, z: g0.z }, gsite("B")],
  ["T1 spawn → bomb B HOL", { x: g1.x, y: g1.y, z: g1.z }, gsite("B")],
  ["T0 spawn → bomb A BALKON", { x: g0.x, y: g0.y, z: g0.z }, gsite("A")],
  ["T1 spawn → bomb A BALKON", { x: g1.x, y: g1.y, z: g1.z }, gsite("A")],
  ["bomb B HOL → bomb A BALKON", gsite("B"), gsite("A")],
  ["T0 spawn → flag C HOL (the contested one)", { x: g0.x, y: g0.y, z: g0.z }, gflag("C")],
  ["T0 spawn → flag B SKŁAD (the far flag)", { x: g0.x, y: g0.y, z: g0.z }, gflag("B")],
  ["T0 spawn → T1 spawn (first contact)", { x: g0.x, y: g0.y, z: g0.z }, { x: g1.x, y: g1.y, z: g1.z }],
  ["KUCHNIA → SKŁAD (the well is in the way)", { x: -13, y: 0, z: 7 }, { x: 13, y: 0, z: 7 }],
  ["BALKON → DACH (fire escape)", { x: 8, y: 0, z: 10 }, { x: 14, y: 3, z: 5 }],
  ["SKŁAD → DACH (loft stair)", { x: 10, y: 0, z: 6 }, { x: 12, y: 3, z: 1.5 }],
  ["DACH → the balcony below", { x: 12, y: 3, z: 1.5 }, { x: 0, y: 0, z: 10 }],
] as [string, { x: number; y: number; z: number }, { x: number; y: number; z: number }][]) {
  const path = findPath(gwalk, from, to, 60000);
  if (!path) { console.log(`| ${name} | — | NO PATH | — |`); continue; }
  const pts: P[] = path.map((p) => [p.x, p.z]);
  const r = runRoute(gora, pts, from.y);
  console.log(`| ${name} | ${Math.hypot(to.x - from.x, to.z - from.z).toFixed(1)} | ${polyLen(pts).toFixed(1)} | ${r.stuck ? (polyLen(pts) / 7.6).toFixed(1) + " (est)" : r.s.toFixed(1)} |`);
}
{
  const cells: { x: number; z: number; y: number }[] = [];
  for (const [key, ys] of gwalk.cells) {
    const [cx, cz] = key.split(",").map(Number);
    for (const y of ys) cells.push({ x: cx / 2, z: cz / 2, y });
  }
  // Only surfaces a player can actually stand on: the cell AND the height have to be reachable,
  // or the tops of the ceiling slab (y 4.4, unreachable by design) pollute the sample.
  const reach = reachable(gwalk, GORA.spawns[0]);
  const live = cells.filter((c) => reach.has(`${cellKey(c.x, c.z)}@${c.y}`));
  const rnd = rnd32(12345);
  const clear: number[] = [];
  let max = 0, pair = "";
  const N = 400000;
  for (let i = 0; i < N; i++) {
    const a = live[(rnd() * live.length) | 0], b = live[(rnd() * live.length) | 0];
    const dx = b.x - a.x, dy = b.y - a.y, dz = b.z - a.z;
    const len = Math.hypot(dx, dy, dz);
    if (len < 1) continue;
    if (!gora.raycast(a.x, a.y + PLAYER.eyeHeight, a.z, dx / len, dy / len, dz / len, len - 0.05, makeRayHit()).hit) {
      clear.push(len);
      if (len > max) { max = len; pair = `(${a.x},${a.y},${a.z}) → (${b.x},${b.y},${b.z})`; }
    }
  }
  clear.sort((p, q) => p - q);
  const pc = (f: number) => clear[Math.floor(clear.length * f)].toFixed(1);
  const over = (m: number) => ((clear.filter((c) => c >= m).length / clear.length) * 100).toFixed(1);
  console.log(`\n**Sight lines.** ${gwalk.cells.size} walkable cells (${live.length} surfaces reachable from spawn 0 = ${(live.length * WALK_GRID * WALK_GRID).toFixed(0)} m²). ${N} random eye-to-eye pairs, ${clear.length} unobstructed (${((clear.length / N) * 100).toFixed(1)} %):`);
  console.log(`median **${pc(0.5)} m**, p90 ${pc(0.9)} m, p99 ${pc(0.99)} m, longest **${max.toFixed(1)} m** ${pair}.`);
  console.log(`Of the clear lines, ${over(10)} % are over 10 m, ${over(20)} % over 20 m, ${over(30)} % over 30 m.\n`);
}
