import { chromium } from "@playwright/test";
const OUT = "/tmp/claude-0/-home-user-sidequest/1d2f80ee-f8c5-5282-b5fc-eb567dff361c/scratchpad/shots";
const pp = process.env.PP !== "0";
const SET = JSON.stringify({ graphics: { preset: "high", renderer: "webgl2", renderScale: 1, shadows: process.env.SH === "0" ? "off" : "medium", postProcessing: pp, effects: 1, antialiasing: true } });
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } });
await ctx.addInitScript((v) => localStorage.setItem("fb_settings_v1", v), SET);
const page = await ctx.newPage();
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
await page.goto("http://localhost:5174/");
await page.getByTestId("btn-play").click();
await page.getByTestId("input-name").fill("SHOT");
await page.getByTestId("input-room").fill("shot1-" + Date.now());
await page.getByTestId("btn-quickplay").click();
await page.waitForFunction(() => window.__fb?.game && window.__fb.hud.get().loadStage === "ready", null, { timeout: 60000 });
await page.evaluate(() => { const c = document.querySelector("canvas"); Object.defineProperty(document, "pointerLockElement", { get: () => c, configurable: true }); document.dispatchEvent(new Event("pointerlockchange")); });
const frames = async (n) => { const s = await page.evaluate(() => window.__fb.game.frameCount); await page.waitForFunction((t) => window.__fb.game.frameCount >= t, s + n, { timeout: 120000 }); };
const [x, y, z, yaw, pitch] = (process.env.VIEW || "2,0.05,1.2,0.3,0.05").split(",").map(Number);
await page.evaluate(([x, y, z]) => window.__fb.game.conn.send("dev:teleport", { x, y, z }), [x, y, z]);
await page.waitForTimeout(500);
await page.evaluate(([yaw, pitch]) => { window.__fb.game.localPlayer.yaw = yaw; window.__fb.game.localPlayer.pitch = pitch; }, [yaw, pitch]);
if (process.env.FOG === "0") await page.evaluate(() => { window.__fb.game.currentScene.fogMode = 0; });
if (process.env.EVAL) await page.evaluate(process.env.EVAL);
await frames(3);
await page.screenshot({ path: `${OUT}/${process.env.NAME || "x"}.png` });
console.log("ok", process.env.NAME, await page.evaluate(() => { const b = window.__fb.game.localPlayer.body; return [b.x.toFixed(1), b.z.toFixed(1)].join(","); }));
await browser.close();
