import type { CollectionId, SkinDef } from "./types";

export const COLLECTIONS: readonly { id: CollectionId; name: string; blurb: string }[] = [
  { id: "zaklad", name: "Zakład", blurb: "Pierwsze wykończenia z zaplecza Frankiego." },
  { id: "barber", name: "Barber Underground", blurb: "Brzytwy, czaszki i pompadoury. Ulica strzyże." },
  { id: "osiedle", name: "Nocna Zmiana", blurb: "Bloki, klatki, neony i bazgroły Marcovii." },
  { id: "monopol", name: "Monopolowy", blurb: "Etykiety, kapsle i neon nocnego sklepu." },
  { id: "zielony", name: "Zielony Salon", blurb: "Liście, dym, oczy i spirale." },
  { id: "masa", name: "Masa", blurb: "Ciężary, serum i przerysowana forma." },
  { id: "pogodzinach", name: "Po Godzinach", blurb: "Usta, serca i neony klubowe. Dla dorosłych." },
  { id: "zlota", name: "Złota Półka", blurb: "Grawerunek, chrom i złoto. Nagrody do pokazania." },
];
export const collectionName = (id: CollectionId): string => COLLECTIONS.find(c => c.id === id)?.name ?? id;

const L = "layered";
const MAG_FED = ["pistol", "machinepistol", "smg", "smg2", "carbine", "rifle", "lmg", "dmr", "sniper"] as const;

/**
 * Every recipe is a stack of named layers over the weapon's side elevation (see `layered`): a base
 * material, a supporting pattern on the stock and fore-end, a hero motif on the receiver, marks on
 * the magazine and stock, stickers, a serial, the collection's sign, edge bevels and wear. Colour
 * slots are `base,ink,accent,light,extra`. IDs are stable: saved collections refer to them.
 */
export const catalog: readonly SkinDef[] = [
  // ---- Zakład: the original six plus the workshop basics, rebuilt as real pieces -------------
  { id: "warsztat", name: "Warsztat", rarity: "pospolity", collection: "zaklad", generator: L, seed: 1987, weapons: "all", blurb: "Zapach oleju i poniedziałku.",
    params: { receiverLegend: "NAPRAWA", base: "polymer", colors: "#4a4f45,#1d1f1c,#d9a441,#e6e1d2,#8a8f86", hero: "wrench", heroScale: 1.0, stockText: "WARSZTAT", stencil: "SERWIS", stickers: "gear,!OLEJ", wear: .38, partTint: .8 } },
  { id: "stalowka", name: "Stalówka", rarity: "pospolity", collection: "zaklad", generator: L, seed: 1044, weapons: "all", blurb: "Czysta stal, numer i nity. Nic więcej.",
    params: { receiverLegend: "STAL 1987", base: "steel", colors: "#a9b0b8,#2b3036,#c8102e,#f0f2f4,#5d666f", hero: "hexnut", heroScale: .7, heroDz: -.3, panel: "dark", panelAlpha: .25, panelRivets: true, textColor: "#2b3036", textStroke: false, pattern: "grid", patternOn: "stock", patternColors: "#5d666f", patternScale: .3, patternAlpha: .5, wear: .2, partTint: .5 } },
  { id: "talk", name: "Talk", rarity: "pospolity", collection: "zaklad", generator: L, seed: 2026, weapons: "all", blurb: "Biała jak ręcznik, który zaraz przestanie być biały.",
    params: { receiverLegend: "TALK", base: "paper", colors: "#e8e2d6,#2d3a4a,#4d8ec9,#ffffff,#c9d8e6", hero: "towel", heroScale: 1.05, pattern: "stripes", patternOn: "stock,front", patternColors: "#4d8ec9,#e8e2d6", patternScale: .22, patternAngle: 0, patternAlpha: .6, stockText: "ŚWIEŻY RĘCZNIK", textColor: "#2d3a4a", textStroke: false, stickers: "!TALK", wear: .1 } },
  { id: "beton", name: "Beton", rarity: "pospolity", collection: "zaklad", generator: L, seed: 81, weapons: "all", blurb: "Surowy, niezawodny i pomazany.",
    params: { base: "concrete", colors: "#697077,#2a2d31,#e0c400,#d7dadd,#4a4f55", hero: "tag", heroLabel: "BETON", heroScale: 1.1, pattern: "bricks", patternOn: "front", patternColors: "#5c6268,#61686e", patternScale: .3, patternAlpha: .8, stickers: "!13", drips: true, dripColor: "#e0c400", wear: .3 } },
  { id: "oliwka", name: "Oliwka", rarity: "pospolity", collection: "zaklad", generator: L, seed: 82, weapons: "all", blurb: "Klasyka zaplecza, z numerem magazynu.",
    params: { receiverLegend: "MAG-01", base: "polymer", colors: "#596044,#2b2f21,#d9c46b,#e8e2d6,#7f8a5e", hero: "star-badge", heroLabel: "01", heroScale: .85, pattern: "camo", patternOn: "stock,front", patternColors: "#4b5238,#6b7350,#3b4030", patternScale: .3, stockText: "OLIWKA", stencil: "WŁASNOŚĆ ZAKŁADU", stickers: "!NIE DOTYKAĆ", wear: .25 } },
  { id: "rdza", name: "Rdza", rarity: "pospolity", collection: "zaklad", generator: L, seed: 83, weapons: "all", blurb: "Po przejściach. Wciąż strzela.",
    params: { receiverLegend: "ZŁOM", base: "steel", colors: "#7f4f30,#3a1f12,#c8763a,#e3d3bd,#4b2a18", hero: "gear", heroScale: 1.0, pattern: "splatter", patternOn: "all", patternColors: "#5a2f18,#c8763a,#3a1f12", patternScale: .5, patternAlpha: .8, stencil: "NIE ZŁOMOWAĆ", stickers: "!RDZA", wear: .7, grain: .8 } },
  { id: "osy", name: "Osy", rarity: "rzadki", collection: "zaklad", generator: L, seed: 7331, weapons: "all", blurb: "Nie drażnić.",
    params: { receiverLegend: "OSY", base: "lacquer", colors: "#f2b400,#141414,#f2b400,#fff3c4,#ff7a00", hero: "wasp", heroScale: 1.2, pattern: "hazard", patternOn: "stock,front", patternColors: "#141414,#f2b400", patternScale: .32, stockText: "NIE DRAŻNIĆ", textColor: "#141414", textStroke: false, stickers: "!UWAGA OSY", accentBand: true, wear: .12 } },
  { id: "szlaczek-babci", name: "Szlaczek Babci", rarity: "rzadki", collection: "zaklad", generator: L, seed: 1938, weapons: "all", blurb: "Wzór z serwetki, przeniesiony na broń.",
    params: { receiverLegend: "SZLACZEK", base: "wood", colors: "#7a5c3a,#3a2a1a,#c8102e,#f3e9d2,#0a3d91", hero: "flower-folk", heroScale: 1.15, pattern: "folk", patternOn: "stock,front", patternColors: "#c8102e,#f3e9d2,#0a3d91", patternScale: .28, stockText: "BABCIA", textColor: "#f3e9d2", partTint: .9, wear: .15 } },
  { id: "landrynka", name: "Landrynka", rarity: "rzadki", collection: "zaklad", generator: L, seed: 93, weapons: "all", blurb: "Słodka tylko z daleka.",
    params: { receiverLegend: "LANDRYNKA", base: "lacquer", colors: "#3c183d,#1d0b1e,#ef4d9b,#fff1f7,#5de1d0", hero: "lollipop", heroScale: 1.25, heroRot: -.6, pattern: "dots", patternOn: "stock,front", patternColors: "#ef4d9b,#5de1d0", patternScale: .3, stockText: "SŁODKA", stickers: "candy,!SŁODKA", wear: .05 } },
  { id: "tokio", name: "Tokio po Północy", rarity: "epicki", collection: "zaklad", generator: L, seed: 102, weapons: "all", blurb: "Neon odbity w mokrym asfalcie.",
    params: { base: "neon", colors: "#071726,#03101c,#ff287f,#e6fbff,#00d9ff", glow: "#00d9ff", hero: "neon-club", heroLabel: "TOKIO", heroScale: 1.4, pattern: "circuit", patternOn: "stock,front", patternColors: "#00d9ff,#ff287f", patternScale: .25, patternAlpha: .7, frontText: "PO PÓŁNOCY", glowText: true, stockMotif: "moon", stockScale: .55, stickers: "lightning,!NOC", wear: .05 } },
  { id: "krwawy-zachod", name: "Krwawy Zachód", rarity: "epicki", collection: "zaklad", generator: L, seed: 104, weapons: "all", blurb: "Ostatni klient już wyszedł.",
    params: { receiverLegend: "ZACHÓD", base: "lacquer", colors: "#2a0b10,#120507,#b20f2c,#ffd9a8,#ff8b45", pattern: "rays", patternOn: "receiver", patternColors: "#b20f2c,#ff8b45", patternAlpha: .85, hero: "palm", heroScale: 1.3, heroDz: .2, drips: true, dripColor: "#b20f2c", stockText: "OSTATNI KLIENT", stockMotif: "sunburst", stockScale: .5, stockMotifDz: -.2, stickers: "moon", wear: .15 } },
  { id: "zorza", name: "Zorza", rarity: "legendarny", collection: "zaklad", generator: L, seed: 112, weapons: "all", blurb: "Kolor, który nie powinien istnieć.",
    params: { base: "neon", colors: "#071326,#04101c,#13e0a1,#e8f6ff,#4b69ff", glow: "#d64cff", hero: "aurora", heroScale: 1.6, heroGlow: true, stockMotif: "mountains", stockScale: .9, magMotif: "moon", magScale: .6, frontMotif: "aurora", frontScale: .7, pattern: "dots", patternOn: "grip", patternColors: "#e8f6ff", patternScale: .12, patternAlpha: .5, wear: .03, partTint: .4 } },

  // ---- Barber Underground -----------------------------------------------------------------------
  { id: "slupek-frankiego", name: "Słupek Frankiego", rarity: "rzadki", collection: "barber", generator: L, seed: 1987, weapons: "all", blurb: "Kręci się od 1987 i nikt nie wie po co.",
    params: { receiverLegend: "FRANKI", base: "lacquer", colors: "#e8e2d6,#1a1c22,#c8102e,#ffffff,#0a3d91", hero: "barber-badge", heroScale: 1.2, pattern: "helix", patternOn: "stock,front,grip", patternColors: "#c8102e,#0a3d91,#e8e2d6", patternScale: .5, patternAngle: 62, stockText: "OD 1987", textColor: "#1a1c22", textStroke: false, stickers: "barber-pole", wear: .08 } },
  { id: "brzytwa", name: "Brzytwa", rarity: "rzadki", collection: "barber", generator: L, seed: 92, weapons: "all", blurb: "Ostry srebrny rytm.",
    params: { base: "steel", colors: "#20252b,#0f1216,#c8102e,#dce4e8,#8a949c", hero: "razor", heroScale: 1.55, stockMotif: "scissors", stockScale: .8, frontText: "BRZYTWA", accentBand: true, pattern: "stripes", patternOn: "grip", patternColors: "#dce4e8", patternScale: .08, patternAngle: 4, patternAlpha: .5, wear: .1 } },
  { id: "krwawa-brzytwa", name: "Krwawa Brzytwa", rarity: "epicki", collection: "barber", generator: L, seed: 2201, weapons: "all", blurb: "Golenie na krwawo. Zniżka dla stałych.",
    params: { base: "lacquer", colors: "#1a1416,#0b0809,#c8102e,#e8e2d6,#ff3b5c", hero: "bloody-razor", heroScale: 1.55, drips: true, panel: "dark", panelAlpha: .6, pattern: "splatter", patternOn: "stock,front", patternColors: "#c8102e,#8a0a1f", patternScale: .5, stockText: "OSTATNIE CIĘCIE", stickers: "skull-pompadour,!KREW", wear: .18 } },
  { id: "ostatnie-golenie", name: "Ostatnie Golenie", rarity: "rzadki", collection: "barber", generator: L, seed: 2202, weapons: "all", blurb: "Piana, maszynka i cisza po.",
    params: { receiverLegend: "GOLENIE", base: "paper", colors: "#e2dccd,#1d1f24,#c8102e,#ffffff,#2f7fbf", hero: "clippers", heroScale: 1.2, heroRot: -1.2, pattern: "stripes", patternOn: "stock", patternColors: "#c8102e,#e2dccd", patternScale: .25, patternAngle: 0, patternAlpha: .7, stockText: "OSTATNIE", textColor: "#1d1f24", textStroke: false, stickers: "mustache,comb", frontMotif: "hair-wave", frontScale: .9, wear: .1 } },
  { id: "barber-cartel", name: "Barber Cartel", rarity: "epicki", collection: "barber", generator: L, seed: 2203, weapons: "all", blurb: "Złote nożyczki, czarny interes.",
    params: { receiverLegend: "CARTEL", base: "lacquer", colors: "#0e0f12,#2a1b1b,#c9a24a,#f4e8c8,#7a1d2b", hero: "skull-pompadour", heroScale: 1.3, pattern: "chevron", patternOn: "stock,front", patternColors: "#c9a24a,#0e0f12", patternScale: .3, patternAlpha: .8, stockText: "BARBER", frontText: "EST. 1987", textColor: "#c9a24a", stickers: "barber-badge", magMotif: "scissors", magScale: .7, accentBand: true, wear: .06 } },
  { id: "pompadour-inferno", name: "Pompadour Inferno", rarity: "legendarny", collection: "barber", generator: L, seed: 2204, weapons: "all", blurb: "Fryzura, która się nie gasi.",
    params: { receiverLegend: "INFERNO", base: "lacquer", colors: "#140805,#1b0b06,#ff6a00,#fff0b0,#ffc400", glow: "#ff9a00", hero: "flame-quiff", heroScale: 1.35, heroGlow: true, pattern: "flames", patternOn: "stock,front,grip", patternColors: "#ff6a00,#ffc400", patternScale: .5, stockText: "POMPADOUR", magMotif: "skull-pompadour", magScale: .8, stickers: "!GORĄCE", wear: .04 } },
  { id: "fade-master", name: "Fade Master", rarity: "rzadki", collection: "barber", generator: L, seed: 2205, weapons: "all", blurb: "Przejście tak czyste, że aż strzela.",
    params: { base: "polymer", colors: "#2b2f36,#e8e2d6,#5de1d0,#f4f4f4,#7a8089", hero: "comb", heroScale: 1.0, heroRot: -.25, pattern: "stripes", patternOn: "stock", patternColors: "#3b4048,#5a6069,#7a8089,#9aa0a9,#c0c6cf", patternScale: .11, patternAngle: 90, patternAlpha: .9, frontMotif: "hair-wave", frontScale: .8, stockText: "FADE MASTER", stickers: "clippers", wear: .08 } },
  { id: "zly-fryzjer", name: "Zły Fryzjer", rarity: "epicki", collection: "barber", generator: L, seed: 2206, weapons: "all", blurb: "Bez zapisów. Bez litości.",
    params: { receiverLegend: "ZŁY FRYZJER", base: "lacquer", colors: "#4a0f16,#0b0809,#c8102e,#e8e2d6,#ffffff", hero: "scissors", heroScale: 1.3, heroRot: .5, drips: true, stockMotif: "skull-pompadour", stockScale: .85, stockText: "BEZ LITOŚCI", pattern: "zebra", patternOn: "front", patternColors: "#0b0809", patternScale: .45, patternAlpha: .9, stickers: "!BEZ ZAPISÓW", wear: .2 } },

  // ---- Nocna Zmiana (osiedle) -------------------------------------------------------------------
  { id: "nocna-zmiana", name: "Nocna Zmiana", rarity: "rzadki", collection: "osiedle", generator: L, seed: 91, weapons: "all", blurb: "Światła miasta po zamknięciu.",
    params: { base: "neon", colors: "#10141c,#2b4a6b,#315d85,#9fc9df,#ffd36a", glow: "#ffd36a", hero: "skyline", heroScale: 1.35, heroDy: -.1, pattern: "grid", patternOn: "stock", patternColors: "#315d85", patternScale: .4, patternAlpha: .6, stockText: "NOCNA ZMIANA", magMotif: "lamp", magScale: .9, stickers: "moon", wear: .1 } },
  { id: "klatka-13", name: "Klatka 13", rarity: "rzadki", collection: "osiedle", generator: L, seed: 3101, weapons: "all", blurb: "Domofon nie działa. Pukać.",
    params: { receiverLegend: "KLATKA 13", base: "concrete", colors: "#5d6368,#1f2226,#e0c400,#e8e6df,#3b7d3a", glow: "#ffe08a", hero: "stairwell", heroScale: 1.25, pattern: "bricks", patternOn: "stock", patternColors: "#4a4f55,#565c62", patternScale: .3, patternAlpha: .7, stockText: "PUKAĆ", stickers: "flat-number,!SPRZEDAM", drips: true, dripColor: "#3b7d3a", wear: .28 } },
  { id: "betonowy-krol", name: "Betonowy Król", rarity: "epicki", collection: "osiedle", generator: L, seed: 3102, weapons: "all", blurb: "Korona ze sprayu, tron z ławki.",
    params: { receiverLegend: "KRÓL", base: "concrete", colors: "#6a6f74,#1b1d20,#e0c400,#efece4,#2fae4f", hero: "crown", heroScale: 1.2, drips: true, dripColor: "#e0c400", pattern: "splatter", patternOn: "stock,front", patternColors: "#e0c400,#2fae4f,#141414", patternScale: .4, patternAlpha: .85, stockText: "BETON", stickers: "tag,!MRC", wear: .22 } },
  { id: "nocny-patrol", name: "Nocny Patrol", rarity: "rzadki", collection: "osiedle", generator: L, seed: 3103, weapons: "all", blurb: "Cisza nocna od 22. Teoretycznie.",
    params: { receiverLegend: "PATROL", base: "polymer", colors: "#1d2733,#0c1218,#ffd000,#e8ecf0,#8ab4ff", glow: "#ffe9a0", hero: "lamp", heroScale: 1.35, heroDz: -.25, pattern: "hazard", patternOn: "front", patternColors: "#ffd000,#1d2733", patternScale: .3, stockText: "NOCNY", textColor: "#ffd000", magMotif: "antenna", magScale: .8, stickers: "!CISZA NOCNA", wear: .12 } },
  { id: "marcovia-ultras", name: "Marcovia Ultras", rarity: "epicki", collection: "osiedle", generator: L, seed: 3104, weapons: "all", blurb: "Żółto-zieloni do końca świata.",
    params: { receiverLegend: "MARCOVIA", base: "cloth", colors: "#144d2a,#0a2a16,#e3c02c,#f4f1e6,#ffffff", hero: "ultras-shield", heroScale: 1.3, pattern: "stripes", patternOn: "stock,front", patternColors: "#e3c02c,#144d2a", patternScale: .4, patternAngle: 90, stockText: "MRC 13", frontText: "ULTRAS", textColor: "#e3c02c", stickers: "!MRC 13,star-badge", accentBand: true, wear: .1 } },
  { id: "lawka-rezerwowych", name: "Ławka Rezerwowych", rarity: "pospolity", collection: "osiedle", generator: L, seed: 3105, weapons: "all", blurb: "Trzy deski, jeden trener, zero minut.",
    params: { receiverLegend: "REZERWA", base: "wood", colors: "#6b4a2b,#2d1f12,#2fae4f,#f0e8d8,#e0c400", hero: "bench", heroScale: 1.1, heroLabel: "DZIELNICA", frontMotif: "banner", frontScale: .8, stockText: "90 MINUT", stickers: "!ŁAWKA", wear: .35, partTint: .9 } },
  { id: "wielka-plyta", name: "Blok z Wielkiej Płyty", rarity: "rzadki", collection: "osiedle", generator: L, seed: 3106, weapons: "all", blurb: "Jedenaście pięter, jedna winda.",
    params: { receiverLegend: "PŁYTA", base: "concrete", colors: "#7c8288,#2a2e33,#e0c400,#eceae4,#ffe08a", glow: "#ffe08a", hero: "block", heroScale: 1.25, pattern: "grid", patternOn: "stock,front", patternColors: "#5d6368", patternScale: .5, patternAlpha: .6, stockText: "WIELKA", magMotif: "antenna", magScale: .8, stickers: "!M. 13", wear: .2 } },

  // ---- Monopolowy -------------------------------------------------------------------------------
  { id: "czysta-seria", name: "Czysta Seria", rarity: "pospolity", collection: "monopol", generator: L, seed: 4101, weapons: "all", blurb: "Etykieta biała, zamiary czyste.",
    params: { receiverLegend: "CZYSTA", base: "paper", colors: "#f1ede3,#1b1b1f,#c8102e,#ffffff,#1c4f9c", hero: "label", heroLabel: "CZYSTA", heroScale: 1.15, stockText: "SERIA 40%", textColor: "#1b1b1f", textStroke: false, stickers: "cap", accentBand: true, wear: .08 } },
  { id: "ostatni-kieliszek", name: "Ostatni Kieliszek", rarity: "rzadki", collection: "monopol", generator: L, seed: 4102, weapons: "all", blurb: "Ostatni. Naprawdę ostatni.",
    params: { receiverLegend: "OSTATNI", base: "lacquer", colors: "#15181f,#0a0c11,#d7e6f2,#ffffff,#7fc4ff", hero: "clink", heroScale: 1.3, pattern: "dots", patternOn: "stock", patternColors: "#d7e6f2", patternScale: .18, patternAlpha: .35, stockText: "KIELISZEK", frontText: "NA DROGĘ", italic: true, stickers: "shot", wear: .1 } },
  { id: "weselny-magazynek", name: "Weselny Magazynek", rarity: "epicki", collection: "monopol", generator: L, seed: 4103, weapons: [...MAG_FED], blurb: "Sto lat, sto lat, trzydzieści nabojów.",
    params: { receiverLegend: "100 LAT", base: "lacquer", colors: "#f4efe6,#2b1a1a,#c8102e,#ffffff,#e3c02c", hero: "wedding", heroScale: 1.3, pattern: "folk", patternOn: "stock", patternColors: "#c8102e,#e3c02c,#1c4f9c", patternScale: .28, stockText: "NA ZDROWIE!", textColor: "#c8102e", textStroke: false, magText: "WESELE", magMotif: "heart", magScale: .45, magMotifDy: .3, stickers: "!GORZKO,cherry", wear: .06 } },
  { id: "spirytus-taktyczny", name: "Spirytus Taktyczny", rarity: "legendarny", collection: "monopol", generator: L, seed: 4104, weapons: "all", blurb: "95%. Łatwopalne. Celne.",
    params: { base: "steel", colors: "#31363b,#14171a,#c8102e,#f3f1ec,#ffd000", hero: "bottle", heroLabel: "SPIRYTUS", heroScale: 1.2, heroRot: -1.5708, pattern: "hazard", patternOn: "front", patternColors: "#ffd000,#1d2024", patternScale: .3, stockText: "95% TAKTYCZNY", stockMotif: "flask", stockScale: .5, stockMotifDz: -.3, stickers: "!ŁATWOPALNE,flask", accentBand: true, wear: .12 } },
  { id: "nocny-monopol", name: "Nocny Monopol", rarity: "epicki", collection: "monopol", generator: L, seed: 4105, weapons: "all", blurb: "Otwarte, kiedy wszystko inne zamknięte.",
    params: { receiverLegend: "NOCNY", base: "neon", colors: "#0b0f1a,#070a12,#ff2d95,#eaf2ff,#00d9ff", glow: "#ff2d95", hero: "neon-24", heroScale: 1.25, heroGlow: true, glowText: true, stockText: "MONOPOL", frontText: "OTWARTE", pattern: "grid", patternOn: "stock", patternColors: "#1f2a44", patternScale: .4, patternAlpha: .8, stickers: "bottle,cap", wear: .05 } },
  { id: "setka-na-celnosc", name: "Setka na Celność", rarity: "rzadki", collection: "monopol", generator: L, seed: 4106, weapons: ["sniper", "dmr", "pistol", "revolver", "carbine"], blurb: "Ręka pewna, oko jedno.",
    params: { receiverLegend: "SETKA", base: "polymer", colors: "#3a3d42,#1a1c20,#e3c02c,#f3f1ec,#c8102e", hero: "cap", heroScale: 1.15, magMotif: "shot", magScale: .8, stockMotif: "target", stockScale: .85, stickers: "!100 ML", wear: .14 } },
  { id: "kaucja", name: "Kaucja", rarity: "pospolity", collection: "monopol", generator: L, seed: 4107, weapons: "all", blurb: "Zwrot butelki: pięćdziesiąt groszy.",
    params: { base: "paper", colors: "#dcd4c2,#2b3a2b,#2f7d4f,#f5f1e6,#c9a24a", hero: "banknote", heroScale: 1.15, stockText: "KAUCJA 0,50", textColor: "#2b3a2b", textStroke: false, stickers: "cap,!ZWROT", pattern: "plaid", patternOn: "grip", patternColors: "#2f7d4f,#c9a24a", patternScale: .2, patternAlpha: .5, wear: .3 } },

  // ---- Zielony Salon ----------------------------------------------------------------------------
  { id: "fioletowy-dym", name: "Fioletowy Dym", rarity: "epicki", collection: "zielony", generator: L, seed: 101, weapons: "all", blurb: "Zostaje w pamięci.",
    params: { receiverLegend: "DYM", base: "lacquer", colors: "#160d25,#0a0612,#7138a8,#efe0ff,#d68cff", glow: "#d68cff", hero: "smoke", heroScale: 1.45, heroGlow: true, stockMotif: "eye", stockScale: .8, pattern: "waves", patternOn: "front", patternColors: "#7138a8,#d68cff", patternScale: .3, patternAlpha: .7, stockText: "FIOLETOWY", textSize: .03, stickers: "leaf", wear: .08 } },
  { id: "zielony-dym", name: "Zielony Dym", rarity: "rzadki", collection: "zielony", generator: L, seed: 5101, weapons: "all", blurb: "Wchodzi powoli, zostaje na długo.",
    params: { receiverLegend: "ZIELONY", base: "polymer", colors: "#12301c,#071a0d,#3fbf5a,#e3ffe6,#7dff8a", glow: "#7dff8a", hero: "smoke", heroScale: 1.35, stockMotif: "leaf", stockScale: .85, frontMotif: "leaf", frontScale: .8, stockText: "DYM", textSize: .028, stickers: "!420", wear: .1 } },
  { id: "sativa-strike", name: "Sativa Strike", rarity: "epicki", collection: "zielony", generator: L, seed: 5102, weapons: "all", blurb: "Naturalna przewaga. Nie do wykrycia.",
    params: { receiverLegend: "SATIVA", base: "lacquer", colors: "#0f1a12,#071009,#3fbf5a,#eaffdf,#9dff4a", glow: "#9dff4a", hero: "leaf", heroScale: 1.4, heroGlow: true, pattern: "hex", patternOn: "stock,front", patternColors: "#1f4a2a,#2f7d3f", patternScale: .25, stockText: "SATIVA", frontText: "STRIKE", textColor: "#9dff4a", stickers: "eye,!NATURALNY", wear: .05 } },
  { id: "mocny-buch", name: "Mocny Buch", rarity: "rzadki", collection: "zielony", generator: L, seed: 5103, weapons: "all", blurb: "Grzybek uśmiecha się do wszystkich.",
    params: { receiverLegend: "BUCH!", base: "lacquer", colors: "#2a1240,#150822,#ff4fd8,#fff0ff,#5de1d0", hero: "mushroom-face", heroScale: 1.3, pattern: "dots", patternOn: "stock", patternColors: "#ff4fd8,#5de1d0,#ffe94a", patternScale: .3, stockText: "MOCNY", drips: true, dripColor: "#5de1d0", stickers: "smoke,!BUCH", wear: .06 } },
  { id: "lesny-doktor", name: "Leśny Doktor", rarity: "pospolity", collection: "zielony", generator: L, seed: 5104, weapons: "all", blurb: "Przyjmuje w krzakach, bez skierowania.",
    params: { receiverLegend: "DOKTOR", base: "polymer", colors: "#3d4d2c,#1a2312,#7dbb4a,#e8f0dc,#c9e37d", hero: "bud", heroScale: 1.25, heroRot: -1.5708, pattern: "camo", patternOn: "stock,front", patternColors: "#2e3d20,#4a5f30,#1f2a16", patternScale: .3, stockText: "LEŚNY", magMotif: "flask", magScale: .7, stickers: "leaf,!RP", wear: .25 } },
  { id: "hydroponiczny", name: "Hydroponiczny", rarity: "rzadki", collection: "zielony", generator: L, seed: 5105, weapons: "all", blurb: "Woda, LED i cierpliwość.",
    params: { receiverLegend: "HYDRO", base: "steel", colors: "#2a3540,#111a20,#8cff6a,#e6f6ff,#3fbf5a", glow: "#8cff6a", hero: "flask", heroScale: 1.2, pattern: "circuit", patternOn: "stock,front", patternColors: "#8cff6a,#3fbf5a", patternScale: .3, patternAlpha: .6, stockText: "KROPLA", frontText: "H2O + LED", glowText: true, magMotif: "leaf", magScale: .7, stickers: "!LAB", wear: .06 } },
  { id: "oczy-czerwone", name: "Oczy Czerwone", rarity: "legendarny", collection: "zielony", generator: L, seed: 5106, weapons: "all", blurb: "Nie śpi. Nigdy nie śpi.",
    params: { receiverLegend: "NIE ŚPIĘ", base: "lacquer", colors: "#1b0b0b,#0d0505,#ff3b3b,#fff0f0,#ffb347", glow: "#ff3b3b", hero: "eye", heroScale: 1.35, heroGlow: true, stockMotif: "eye", stockScale: .6, frontMotif: "smoke", frontScale: .9, magMotif: "leaf", magScale: .7, pattern: "waves", patternOn: "grip", patternColors: "#ff3b3b", patternScale: .2, patternAlpha: .4, stickers: "spiral,!24/7", wear: .04 } },

  // ---- Masa -------------------------------------------------------------------------------------
  { id: "cykl-bojowy", name: "Cykl Bojowy", rarity: "rzadki", collection: "masa", generator: L, seed: 6101, weapons: "all", blurb: "Dwanaście tygodni do formy życia.",
    params: { base: "polymer", colors: "#23262b,#0f1114,#66ff99,#e8ffe8,#ffd000", glow: "#66ff99", hero: "syringe", heroScale: 1.2, pattern: "hazard", patternOn: "stock", patternColors: "#66ff99,#23262b", patternScale: .3, stockText: "CYKL BOJOWY", magMotif: "flask", magScale: .7, stickers: "pill,!DAWKA 2X", wear: .1 } },
  { id: "masa-krytyczna", name: "Masa Krytyczna", rarity: "epicki", collection: "masa", generator: L, seed: 6102, weapons: "all", blurb: "Trzydzieści dwa kilo w jednej ręce.",
    params: { receiverLegend: "MASA", base: "steel", colors: "#3a3f45,#141618,#ffd000,#f3f1ec,#c8102e", hero: "kettlebell", heroScale: 1.25, stockMotif: "dumbbell", stockScale: .9, pattern: "chevron", patternOn: "front", patternColors: "#ffd000,#141414", patternScale: .25, stockText: "32 KG", stickers: "!CIĘŻKIE", accentBand: true, wear: .15 } },
  { id: "tren-express", name: "Tren Express", rarity: "pospolity", collection: "masa", generator: L, seed: 6103, weapons: "all", blurb: "Bez przesiadek, prosto na masę.",
    params: { receiverLegend: "TREN", base: "cloth", colors: "#1f3a5a,#0e1c2c,#ff8c00,#eaf1f8,#ffd000", hero: "shaker", heroScale: 1.2, heroRot: -1.5708, pattern: "stripes", patternOn: "stock,front", patternColors: "#ff8c00,#1f3a5a", patternScale: .35, stockText: "EXPRESS", stickers: "!GAINZ,dumbbell", wear: .15 } },
  { id: "apteczny-wojownik", name: "Apteczny Wojownik", rarity: "rzadki", collection: "masa", generator: L, seed: 6104, weapons: "all", blurb: "Recepta na wszystko.",
    params: { receiverLegend: "RECEPTA", base: "paper", colors: "#e9e6dd,#1b1b1f,#c8102e,#ffffff,#1c4f9c", hero: "pill", heroScale: 1.25, pattern: "dots", patternOn: "stock", patternColors: "#c8102e,#1c4f9c", patternScale: .2, patternAlpha: .6, stockText: "APTECZNY", frontText: "WOJOWNIK", textColor: "#1b1b1f", textStroke: false, magMotif: "syringe", magScale: .9, magMotifRot: 1.5708, stickers: "!RECEPTA,flask", wear: .08 } },
  { id: "biceps-kaliber", name: "Biceps Kaliber", rarity: "epicki", collection: "masa", generator: L, seed: 6105, weapons: "all", blurb: "Czterdzieści pięć centymetrów obwodu.",
    params: { receiverLegend: "KALIBER", base: "lacquer", colors: "#3b0f14,#1a0709,#ffc400,#f5ead6,#ff6a00", hero: "flex-arm", heroScale: 1.3, pattern: "flames", patternOn: "stock", patternColors: "#ff6a00,#ffc400", patternScale: .5, patternAlpha: .85, stockText: "BICEPS", frontText: "OBWÓD", stickers: "kettlebell,!45 CM", accentBand: true, wear: .1 } },
  { id: "dzien-nog", name: "Dzień Nóg", rarity: "legendarny", collection: "masa", generator: L, seed: 6106, weapons: "all", blurb: "Nigdy nie opuszczaj. Nigdy.",
    params: { receiverLegend: "DZIEŃ NÓG", base: "chrome", colors: "#8f979f,#141618,#e0a020,#fff6e0,#66ff99", glow: "#66ff99", hero: "lifter", heroScale: 1.35, pattern: "leopard", patternOn: "stock", patternColors: "#e0a020,#141414", patternScale: .25, stockText: "NIGDY", frontText: "NIE OPUSZCZAJ", textColor: "#141618", textStroke: false, magMotif: "dumbbell", magScale: .9, magMotifRot: 1.5708, stickers: "syringe,!45 KG", partTint: .4, wear: .04 } },

  // ---- Po Godzinach (18+) -----------------------------------------------------------------------
  { id: "dlugi-magazynek", name: "Długi Magazynek", rarity: "rzadki", collection: "pogodzinach", generator: L, seed: 7101, weapons: ["lmg", "smg", "smg2", "machinepistol", "rifle", "carbine"], nsfw: true, blurb: "Rozmiar podobno nie ma znaczenia.",
    params: { receiverLegend: "XXL", base: "lacquer", colors: "#2a0d1e,#12060d,#ff4fa3,#ffe6f2,#ff9ad0", glow: "#ff4fa3", hero: "lips", heroScale: 1.25, magText: "DŁUGI", magMotif: "heart", magScale: .45, magMotifDy: -.3, pattern: "dots", patternOn: "stock", patternColors: "#ff4fa3", patternScale: .22, patternAlpha: .6, stockText: "MAGAZYNEK", stickers: "!DŁUGI,kiss-mark", wear: .06 } },
  { id: "mokre-golenie", name: "Mokre Golenie", rarity: "rzadki", collection: "pogodzinach", generator: L, seed: 7102, weapons: "all", nsfw: true, blurb: "Ciepły ręcznik i coś jeszcze.",
    params: { receiverLegend: "MOKRE", base: "paper", colors: "#f3eef0,#2a1a22,#ff2d6f,#ffffff,#7fc4ff", hero: "kiss-mark", heroScale: 1.3, pattern: "waves", patternOn: "stock", patternColors: "#7fc4ff,#ff4fa3", patternScale: .3, patternAlpha: .7, stockText: "GOLENIE", textColor: "#ff2d6f", textStroke: false, stickers: "!18+,cherry", wear: .06 } },
  { id: "twarda-sztuka", name: "Twarda Sztuka", rarity: "epicki", collection: "pogodzinach", generator: L, seed: 7103, weapons: "all", nsfw: true, blurb: "Chrom, szpilki i zero wstydu.",
    params: { receiverLegend: "TWARDA", base: "chrome", colors: "#a3a9b0,#141414,#ff2d6f,#ffffff,#ffd000", hero: "pinup-legs", heroScale: 1.35, pattern: "checker", patternOn: "stock", patternColors: "#141414", patternScale: .12, patternAlpha: .9, stockText: "SZTUKA", frontText: "18+", textColor: "#141414", textStroke: false, stickers: "heart,!TYLKO 18+", partTint: .4, wear: .05 } },
  { id: "rozgrzana-lufa", name: "Rozgrzana Lufa", rarity: "epicki", collection: "pogodzinach", generator: L, seed: 7104, weapons: "all", nsfw: true, blurb: "Ostrożnie, parzy.",
    params: { base: "lacquer", colors: "#1a0a0a,#0c0505,#ff3b5c,#ffe0e6,#ff9a00", glow: "#ff3b5c", hero: "neon-club", heroLabel: "GORĄCO", heroScale: 1.2, glowText: true, frontText: "ROZGRZANA LUFA", pattern: "flames", patternOn: "front", patternColors: "#ff3b5c,#ff9a00", patternScale: .45, stickers: "lips,!69", wear: .06 } },
  { id: "tylne-wejscie", name: "Tylne Wejście", rarity: "rzadki", collection: "pogodzinach", generator: L, seed: 7105, weapons: "all", nsfw: true, blurb: "Tylko dla stałych klientów.",
    params: { base: "neon", colors: "#12101c,#080710,#c04dff,#f0e6ff,#ff4fa3", glow: "#c04dff", hero: "neon-club", heroLabel: "WEJŚCIE", heroScale: 1.2, glowText: true, stockText: "TYLNE", pattern: "grid", patternOn: "stock", patternColors: "#2a2440", patternScale: .4, stickers: "!DLA STAŁYCH,heart", wear: .08 } },
  { id: "nocna-usluga", name: "Nocna Usługa", rarity: "legendarny", collection: "pogodzinach", generator: L, seed: 7106, weapons: "all", nsfw: true, blurb: "Całodobowo. Dyskretnie. Ocenzurowano.",
    params: { base: "lacquer", colors: "#0d0a12,#070509,#ff2d95,#ffe6f2,#c04dff", glow: "#ff2d95", hero: "garter", heroScale: 1.2, heroGlow: true, stockMotif: "pinup-legs", stockScale: .85, frontMotif: "censored", frontScale: .75, magMotif: "lips", magScale: .8, pattern: "dots", patternOn: "grip", patternColors: "#ff2d95", patternScale: .15, patternAlpha: .5, stickers: "!24H,kiss-mark", crude: true, wear: .04 } },

  // ---- Złota Półka ------------------------------------------------------------------------------
  { id: "krolewski", name: "Królewski Fach", rarity: "epicki", collection: "zlota", generator: L, seed: 103, weapons: "all", blurb: "Dla mistrza stanowiska.",
    params: { receiverLegend: "KRÓLEWSKI", base: "lacquer", colors: "#20152e,#0f0a17,#d6b768,#fff3cf,#744aa8", hero: "crown", heroScale: 1.15, stockMotif: "filigree", stockScale: .9, frontMotif: "filigree", frontScale: .85, textColor: "#d6b768", textStroke: false, accentBand: true, partTint: .5, wear: .05 } },
  { id: "czarne-zloto", name: "Czarne Złoto", rarity: "legendarny", collection: "zlota", generator: L, seed: 111, weapons: "all", blurb: "Luksus bez kompromisów.",
    params: { base: "carbon", colors: "#0c0c0e,#1a1408,#c99832,#fff0a6,#e5c25c", hero: "filigree", heroScale: 1.35, stockMotif: "laurel", stockScale: .9, frontMotif: "filigree", frontScale: .8, magMotif: "gem", magScale: .7, receiverText: "CZARNE ZŁOTO", receiverTextY: .02, receiverTextSize: .017, textColor: "#e5c25c", textStroke: false, accentBand: true, partTint: .3, wear: .02 } },
  { id: "zlota-setka", name: "Złota Setka", rarity: "legendarny", collection: "zlota", generator: L, seed: 8101, weapons: "all", blurb: "Toast za każde trafienie.",
    params: { receiverLegend: "SETKA", base: "gold", colors: "#b8861b,#2a1a05,#f3d36b,#fff8e0,#ffffff", hero: "clink", heroScale: 1.3, heroLabel: "NA ZDROWIE", stockMotif: "banner", stockScale: .9, magMotif: "cap", magScale: .7, frontMotif: "laurel", frontScale: .8, textColor: "#2a1a05", textStroke: false, partTint: .3, wear: .02 } },
  { id: "zloty-lisc", name: "Złoty Liść", rarity: "legendarny", collection: "zlota", generator: L, seed: 8102, weapons: "all", blurb: "Najdroższy liść w dzielnicy.",
    params: { receiverLegend: "ZŁOTY", base: "gold", colors: "#a67c1e,#2a1a05,#3fbf5a,#fff6d0,#e9c65a", hero: "leaf", heroScale: 1.35, heroGlow: true, glow: "#9dff4a", pattern: "hex", patternOn: "stock,front", patternColors: "#8a6414,#c9992e", patternScale: .25, patternAlpha: .6, textColor: "#2a1a05", textStroke: false, magMotif: "eye", magScale: .7, partTint: .3, wear: .02 } },
  { id: "zlota-brzytwa", name: "Złota Brzytwa", rarity: "zloty", collection: "zlota", generator: L, seed: 8103, weapons: ["sniper", "dmr", "pistol", "revolver", "clippers"], blurb: "Jedno cięcie. Złote.",
    params: { base: "chrome", colors: "#b9bfc6,#1a1408,#e9c65a,#f7f7f2,#c99832", glow: "#fff2a1", hero: "razor", heroScale: 1.35, heroGlow: true, stockMotif: "wings", stockScale: .9, frontMotif: "laurel", frontScale: .8, magMotif: "gem", magScale: .7, receiverText: "ZŁOTA BRZYTWA", receiverTextY: .02, receiverTextSize: .016, textColor: "#1a1408", textStroke: false, pattern: "scales", patternOn: "grip", patternColors: "#c99832,#e9c65a", patternScale: .2, patternAlpha: .6, partTint: .3, wear: 0 } },
  { id: "korona-frankiego", name: "Korona Frankiego", rarity: "zloty", collection: "zlota", generator: L, seed: 1987, weapons: "all", blurb: "Najrzadszy znak zakładu.",
    params: { receiverLegend: "FRANKI", base: "gold", colors: "#c9992e,#3a2a08,#e9c65a,#fff6d0,#ffffff", glow: "#fff2a1", hero: "crown", heroScale: 1.3, heroGlow: true, stockMotif: "laurel", stockScale: .9, frontMotif: "filigree", frontScale: .85, magMotif: "barber-badge", magScale: .8, textColor: "#3a2a08", textStroke: false, pattern: "scales", patternOn: "grip", patternColors: "#a67c1e,#e9c65a", patternScale: .2, patternAlpha: .6, partTint: .3, wear: .02 } },
];
